import { useState, useEffect, useCallback, useContext } from "react";
import { HeartPulse, Sun, Moon, Sparkles, Video, ExternalLink } from "lucide-react";

import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { SourceBadge } from "@/components/ui/SourceBadge";
import { AuthContext } from "../../../context/AuthContext";
import { BACKEND_URL } from "../../../config";
import { authFetch } from "../../../utils/authFetch";
import { getYouTubeEmbedUrl, buildYoutubeSearchUrl } from "@/lib/youtube";

const API = BACKEND_URL || "http://localhost:8080";

// A real video plays inline (embed); if we only have a link (e.g. a
// non-embeddable search-results fallback, or no YOUTUBE_API_KEY configured),
// fall back to a plain "Watch on YouTube" link instead of nothing.
function AsanaEntry({ y }) {
	const embedUrl = getYouTubeEmbedUrl(y.link);
	// Always give the patient somewhere to watch it -- doctor's own link,
	// else a search fallback (covers asanas added with no link at all).
	const watchUrl = !embedUrl ? (y.link || buildYoutubeSearchUrl(y.name)) : null;

	return (
		<div className="flex flex-col gap-2 rounded-(--jh-radius-md) bg-card p-3 shadow-(--jh-shadow-rest)">
			<span className="text-sm font-semibold text-foreground">{y.name}</span>
			{embedUrl ? (
				<div className="aspect-video w-full overflow-hidden rounded-(--jh-radius-sm)">
					<iframe
						src={embedUrl}
						title={y.name}
						className="h-full w-full"
						loading="lazy"
						allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
						allowFullScreen
					/>
				</div>
			) : (
				<a
					href={watchUrl}
					target="_blank"
					rel="noopener noreferrer"
					className="flex items-center gap-1 text-xs font-semibold text-primary hover:underline"
				>
					<Video size={14} /> Watch on YouTube <ExternalLink size={12} />
				</a>
			)}
		</div>
	);
}

function YogaColumn({ title, Icon, entries }) {
	return (
		<div className="flex-1">
			<h5 className="flex items-center gap-1.5 text-sm font-semibold text-foreground">
				<Icon size={18} className="text-primary" /> {title}
			</h5>
			<div className="mt-2 flex flex-col gap-3">
				{entries.map((y, idx) => <AsanaEntry key={idx} y={y} />)}
			</div>
		</div>
	);
}

// Yoga is AI-generated by the patient (from their Prakriti + wellness
// profile), then reviewed/edited/approved by their doctor -- same
// generate-then-review pattern as the Weekly Meal Planner, and the same
// doctor-vs-AI `displayPlan` resolution (see resolveDisplayYogaPlan in
// backend/controllers/ayurvedaYogaPlanController.js). Lifestyle
// recommendations come from the AI diet plan, unrelated to this plan.
function YogaLifestyleTab() {
	const { auth } = useContext(AuthContext);
	const patientId = auth?.user?.id;

	const [yogaPlan, setYogaPlan] = useState(null);
	const [dietPlan, setDietPlan] = useState(null);
	const [loading, setLoading] = useState(true);

	const fetchAll = useCallback(async () => {
		if (!patientId) {
			setLoading(false);
			return;
		}
		setLoading(true);
		try {
			const [yogaRes, dietRes] = await Promise.all([
				authFetch(`${API}/api/ayurveda/yoga-plan`),
				authFetch(`${API}/api/ayurveda/diet-plan`),
			]);
			if (yogaRes.ok) setYogaPlan(await yogaRes.json());
			if (dietRes.ok) setDietPlan(await dietRes.json());
		} catch (error) {
			console.error("Error fetching yoga & lifestyle:", error);
		} finally {
			setLoading(false);
		}
	}, [patientId]);

	useEffect(() => {
		fetchAll();
	}, [fetchAll]);

	if (loading) {
		return <p className="py-6 text-center text-sm text-muted-foreground">Loading...</p>;
	}

	const yoga = yogaPlan?.displayPlan;
	const hasYoga = yoga && ((yoga.morning?.length || 0) + (yoga.evening?.length || 0) > 0);
	const lifestyleRecs = dietPlan?.displayPlan?.lifestyleRecommendations || [];

	return (
		<div className="flex flex-col gap-6">
			<Card>
				<CardHeader>
					<div className="flex flex-wrap items-center justify-between gap-2">
						<CardTitle className="flex items-center gap-2 font-display text-lg">
							<HeartPulse size={18} /> Yoga Practice
						</CardTitle>
						{yogaPlan ? <SourceBadge status={yogaPlan.status || "ai"} /> : null}
					</div>
				</CardHeader>
				<CardContent>
					{hasYoga ? (
						<div className="flex flex-col gap-5 sm:flex-row">
							{yoga.morning?.length ? <YogaColumn title="Morning flow" Icon={Sun} entries={yoga.morning} /> : null}
							{yoga.evening?.length ? <YogaColumn title="Evening flow" Icon={Moon} entries={yoga.evening} /> : null}
						</div>
					) : (
						<EmptyState
							icon={HeartPulse}
							title="No yoga plan yet"
							description="Generate a plan from the wellness intake above to see your personalized yoga sequence here."
						/>
					)}
				</CardContent>
			</Card>

			<Card>
				<CardHeader>
					<div className="flex flex-wrap items-center justify-between gap-2">
						<CardTitle className="flex items-center gap-2 font-display text-lg">
							<Sparkles size={18} /> Lifestyle Recommendations
						</CardTitle>
						{dietPlan ? <SourceBadge status={dietPlan.status || "ai"} /> : null}
					</div>
				</CardHeader>
				<CardContent>
					{lifestyleRecs.length ? (
						<ul className="list-disc pl-5 text-sm text-foreground">
							{lifestyleRecs.map((r, i) => <li key={i}>{r}</li>)}
						</ul>
					) : (
						<EmptyState
							icon={Sparkles}
							title="Not added"
							description="Generate a diet plan from the Weekly Meal Planner tab to see lifestyle recommendations here."
						/>
					)}
				</CardContent>
			</Card>
		</div>
	);
}

export default YogaLifestyleTab;
