const categoryOptions = [
	{ value: "all", label: "All Categories" },
	{ value: "health", label: "Health Tips" },
	{ value: "herbs", label: "Herbs & Remedies" },
	{ value: "diet", label: "Diet & Nutrition" },
	{ value: "yoga", label: "Yoga & Meditation" },
	{ value: "lifestyle", label: "Lifestyle" },
	{ value: "disease management", label: "Disease Management" },
	{ value: "wellness", label: "Wellness" },
	{ value: "ayurveda basics", label: "Ayurveda Basics" },
	{ value: "ayurveda-basics", label: "Ayurveda Basics" },
	{ value: "seasonal-care", label: "Seasonal Care (Ritucharya)" },
	{ value: "daily-routine", label: "Ayurvedic Daily Routine (Dinacharya)" },
	{ value: "skin-hair", label: "Ayurveda for Skin & Hair" },
	{ value: "home-remedies", label: "Ayurvedic Home Remedies" },
	{ value: "detox-panchakarma", label: "Detox & Panchakarma" },
	{ value: "mental-wellness", label: "Stress & Mental Wellness" },
	{ value: "herbs-spices", label: "Ayurvedic Herbs & Spices" },
	{ value: "womens-health", label: "Women’s Health in Ayurveda" },
	{ value: "immunity", label: "Ayurvedic Immunity Boosters" },
	{ value: "digestion", label: "Ayurveda for Digestion" },
	{ value: "sleep-relaxation", label: "Ayurvedic Sleep & Relaxation" },
	{ value: "kids-family", label: "Ayurveda for Kids & Family Care" },
	{ value: "massage-oils", label: "Ayurvedic Oils & Massage (Abhyanga)" },
	{ value: "beauty-skincare", label: "Ayurvedic Beauty & Skincare" },
	{ value: "chronic-conditions", label: "Ayurveda for Chronic Conditions" },
];

export { categoryOptions };
