const mongoose = require('mongoose');
const { parseDob, indianPhoneValidator, indianZipCodeValidator, attachAgeVirtual } = require('./registrationSchemaHelpers');

const RetailerSchema = new mongoose.Schema({
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  BusinessName: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  countryCode: { type: String, required: false }, // e.g. "+91" - required:false at schema level until registration controller sends it (Phase 3)
  phone: {
    type: String,
    required: true,
    validate: { validator: indianPhoneValidator, message: 'Phone number must be exactly 10 digits for India (+91)' }
  },
  dob: { type: Date, required: true, set: parseDob },
  licenseNumber: {
    type: String,
    required: true,
    // No single national format exists - drug/retail licenses are issued per-state under the
    // Drugs & Cosmetics Act. Just bound the length and allow common separators (e.g. "KA-B5-12345").
    validate: {
      validator: (v) => !v || /^[A-Za-z0-9\-/. ]{3,50}$/.test(v),
      message: 'License number must be 3-50 characters (letters, numbers, spaces, - / . allowed)'
    }
  },
  gender: { type: String, required: true, enum: ['Male', 'Female', 'Others'] },
  zipCode: {
    type: String,
    required: true,
    validate: { validator: indianZipCodeValidator, message: 'PIN code must be exactly 6 digits for India (+91)' }
  },
  address: { type: String },
  licenseDocument: { type: String, default: null }, // optional Cloudinary URL for an uploaded license/certificate document
  profileImage: { type: String },
  password: { type: String, required: true },
  status: { type: String, enum: ['active', 'inactive'], default: 'active' },
  role: { type: String, default: 'retailer' },
  razorpayAccountId: {
    type: String,
    default: null
  },
  bankDetails: {
    accountHolderName: { type: String, default: null },
    accountNumber: { type: String, default: null },
    ifscCode: { type: String, default: null },
    businessType: { type: String, default: 'individual' },
    isSubmitted: { type: Boolean, default: false }
  },
  // Per-courier shipping credentials the retailer links so we can pull real
  // tracking instead of trusting a manual "Shipped" click. Nested under a
  // platform key so adding Bluedart/Shiprocket later doesn't reshape anything.
  //
  // Every credential field below is `select: false`: a plain Retailer.findById
  // (including the auth middleware's lookup and getSingleRetailer) must never
  // return them. Code that actually needs to authenticate goes through
  // delhiveryService.findRetailerWithCredentials, which opts back in explicitly.
  shippingIntegrations: {
    delhivery: {
      // Which of the three credential methods this retailer chose.
      method: { type: String, enum: ['apiToken', 'oauth2', 'webhook', null], default: null },

      // Method 1 -- static API token from the Delhivery One dashboard.
      // Stored AES-256-GCM encrypted ("iv:authTag:ciphertext"), see utils/encryption.js.
      apiToken: { type: String, default: null, select: false },

      // Method 2 -- MCP / OAuth2 client credentials, each encrypted separately.
      oauth2ClientId: { type: String, default: null, select: false },
      oauth2ClientSecret: { type: String, default: null, select: false },
      oauth2AuthUrl: { type: String, default: null, select: false },
      oauth2Realm: { type: String, default: null, select: false },

      // Method 3 -- webhook. This secret is generated by us, not supplied by the
      // retailer: they paste it into Delhivery as the X-Secret header so we can
      // tell a genuine push from a forged one. Stored as-is because we need to
      // show it back to them while they set the webhook up.
      webhookSecret: { type: String, default: null, select: false },
      lastWebhookReceivedAt: { type: Date, default: null },

      isConfigured: { type: Boolean, default: false },
      configuredAt: { type: Date, default: null }
    }
  },
  // Pickup / warehouse details the retailer registers with their delivery
  // partner. Required for auto-creating shipments (the pickup_location.name
  // must match the name registered in Delhivery One exactly, case-sensitive).
  warehouse: {
    name: { type: String, default: null },       // Exact name registered in the delivery partner dashboard
    address: { type: String, default: null },     // Street address
    city: { type: String, default: null },
    state: { type: String, default: null },
    pincode: { type: String, default: null },     // 6-digit origin pincode
    phone: { type: String, default: null },       // Contact number at warehouse
    isConfigured: { type: Boolean, default: false }
  },
  resetPasswordOTP: {
    type: String,
    default: null
  },
  resetPasswordOTPExpires: {
    type: Date,
    default: null
  },
  isOTPVerified: {
    type: Boolean,
    default: false
  },
  resetPasswordToken: {
    type: String,
    default: null
  },
  resetPasswordExpires: {
    type: Date,
    default: null
  },
  passwordChangedAt: Date
}, { timestamps: true });

attachAgeVirtual(RetailerSchema);

module.exports = mongoose.model('Retailer', RetailerSchema);
